name: CD - Prod (Manual)

permissions:
  contents: read
  packages: read

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Tag de l'image à déployer (commit SHA de la CI)"
        required: true

concurrency:
  group: deploy-prod
  cancel-in-progress: false

jobs:
  deploy-prod:
    runs-on: self-hosted
    environment:
      name: production   # Configure Required reviewers dans Settings > Environments
      url: http://localhost:8080
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Use selected image tag
        run: echo "IMAGE_TAG=${{ inputs.image_tag }}" >> $GITHUB_ENV

      - name: Pull & deploy
        run: |
          docker compose -f docker-compose.yml pull
          IMAGE_TAG="$IMAGE_TAG" docker compose -f docker-compose.yml up -d --wait --wait-timeout 180
          docker compose -f docker-compose.yml ps

      - name: Quick health probe (host-level)
        run: |
          curl -fsS http://localhost:8080/actuator/health || {
            echo "Backend not healthy (host-level)";
            docker compose -f docker-compose.yml logs backend;
            exit 1;
          }